//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id { get; set; }
        public string evento1 { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
    }
}
