//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imparte
    {
        public int id { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public Nullable<int> id_materia { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
