//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Practico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Examen_ParcialEntities3 : DbContext
    {
        public Examen_ParcialEntities3()
            : base("name=Examen_ParcialEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignatura> Asignaturas { get; set; }
        public virtual DbSet<integrante> integrantes { get; set; }
        public virtual DbSet<profesor> profesors { get; set; }
        public virtual DbSet<cursa> cursas { get; set; }
        public virtual DbSet<imparte> impartes { get; set; }
    }
}
